export const PUBLIC_WEB_ROUTES = [
  "GET /login",
  "GET /forgot-password",
  "GET /reset-password",
  "GET /terms",
  "GET /privacy",
  "GET /pricing",
  "GET /support",
  "GET /account",
  "GET /archive",
  "GET /onboarding",
  "GET /roadmap",
  "GET /team/invite/[token]",
  "GET /api/web/team/invitations/handoff/[token]",
  "POST /api/web/auth/register",
  "POST /api/web/auth/password-reset/request",
  "POST /api/web/auth/password-reset/confirm",
  "POST /api/web/auth/password-reset/handoff",
  "POST /api/web/billing/webhook/[provider]",
  "GET /api/web/applications/calendar-feed/[token]",
  "GET /api/web/stats",
  "POST /api/web/landing-events",
  "GET /api/web/business-lookup-suggestions",
  "POST /api/web/business-lookup-suggestions",
  "POST /api/web/support/tickets",
  "POST /api/web/support/tickets/handoff",
  "POST /api/web/support/tickets/[ticketId]/attachments",
  "POST /api/web/teaser",
  "POST /api/web/company-preview",
  "GET /api/web/credits/products",
  "GET /api/web/plans",
] as const;

export const SESSION_WEB_ROUTES = [
  "GET /applications",
  "GET /billing",
  "GET /dashboard",
  "GET /grants/[grantId]",
  "GET /settings",
  "GET /team",
  "GET /api/web/applications/calendar",
  "GET /api/web/applications/calendar-subscription",
  "GET /api/web/applications/report",
  "GET /api/web/settings/report",
  "GET /api/web/billing/invoices/[invoiceId]/email-handoff",
  "GET /api/web/billing/invoices/[invoiceId]/receipt",
  "GET /api/web/billing/payment-instructions",
  "GET /api/web/billing/plan-requests/[requestId]/email-handoff",
  "GET /api/web/billing/statement",
  "POST /api/web/billing/plan-request",
  "POST /api/web/billing/tax-documents",
  "DELETE /api/web/billing/tax-documents/[documentId]",
  "PUT /api/web/billing/tax-profile",
  "GET /api/web/support/tickets/[ticketId]/transcript",
  "GET /api/web/team/report",
  "GET /api/web/account/security-report",
  "GET /api/web/account/deletion-request/handoff",
  "PATCH /api/web/support/tickets/[ticketId]",
  "DELETE /api/web/support/tickets/[ticketId]/attachments/[attachmentId]",
  "POST /api/web/support/tickets/[ticketId]/messages",
  "POST /api/web/team/invitations",
  "DELETE /api/web/team/invitations/[invitationId]",
  "POST /api/web/team/invitations/[invitationId]/resend",
  "POST /api/web/team/invitations/accept",
  "PATCH /api/web/team/members/[userId]",
  "GET /api/web/account/export",
  "GET /api/web/archive",
  "GET /api/web/archive/facets",
  "GET /api/web/archive/agencies",
  "POST /api/web/account/deletion-request",
  "PUT /api/web/account/password",
  "PUT /api/web/account/profile",
  "GET /api/web/dashboard",
  "GET /api/web/dashboard/report",
  "GET /api/web/companies",
  "POST /api/web/companies",
  "POST /api/web/companies/enrich",
  "POST /api/web/companies/switch",
  "POST /api/web/companies/verify",
  "GET /api/web/consents",
  "PUT /api/web/consents",
  "DELETE /api/web/consents/[scope]",
  "GET /api/web/credits/balance",
  "GET /api/web/credits/estimate",
  "GET /api/web/credits/ledger",
  "GET /api/web/credits/usage",
  "GET /api/web/credits/usage/export",
  "GET /api/web/credits/orders",
  "POST /api/web/credits/checkout",
  "POST /api/web/credits/checkout/complete",
  "POST /api/web/plans/subscribe",
  "POST /api/web/plans/change",
  "POST /api/web/plans/cancel",
  "POST /api/web/plans/billing-key",
  "GET /api/web/matches",
  "GET /api/web/roadmap",
  "POST /api/web/matches/[grantId]/feedback",
  "POST /api/web/matches/[grantId]/events",
  "GET /api/web/action-queue",
  "GET /api/web/next-question",
  "GET /api/web/applications/[grantId]/calendar",
  "GET /api/web/applications/[grantId]/reminder-email",
  "GET /api/web/grants/[grantId]",
  "GET /api/web/grants/[grantId]/preparation",
  "GET /api/web/grants/[grantId]/package",
  "GET /api/web/grants/[grantId]/page-image/[...key]",
  "POST /api/web/grants/[grantId]/drafts",
  "POST /api/web/grants/[grantId]/conversions/poll",
  "GET /api/web/document-drafts/[draftId]",
  "GET /api/web/document-drafts/[draftId]/download",
  "POST /api/web/document-drafts/[draftId]/download",
  "PATCH /api/web/document-drafts/[draftId]",
  "PATCH /api/web/document-drafts/[draftId]/field-answers",
  "POST /api/web/document-drafts/[draftId]/regenerate",
  "POST /api/web/document-drafts/[draftId]/feedback",
  "POST /api/web/document-drafts/[draftId]/field-suggestions",
  "POST /api/web/chat",
  "GET /api/web/notification-feed",
  "GET /api/web/notification-feed/report",
  "POST /api/web/notification-feed/receipt",
  "POST /api/web/profile/field",
  "GET /api/web/notifications",
  "PUT /api/web/notifications",
] as const;

export const PUBLIC_APP_ROUTES = [
  "POST /api/app/v1/auth/login",
  "POST /api/app/v1/auth/[provider]",
  "POST /api/app/v1/auth/refresh",
  "POST /api/app/v1/auth/logout",
  "GET /api/app/v1/openapi.json",
  "GET /api/app/v1/stats",
  "POST /api/app/v1/teaser",
  "POST /api/app/v1/companies/preview",
] as const;

// 시스템/크론 라우트: 세션·회사 접근 정책이 아니라 CRON_SECRET Bearer 로 보호된다(authorizeCronRequest).
// Vercel Cron(apps/web/vercel.json) 또는 수동 트리거만 호출한다. 공개/세션 라우트와 인증 클래스가
// 다르므로 별도 목록으로 분리해 관리하고, verify:route-policy 가 api/cron 스코프와 대조·검증한다.
export const SYSTEM_CRON_ROUTES = [
  "GET /api/cron/ingest-kstartup",
  "GET /api/cron/kstartup-details",
  "GET /api/cron/ingest-bizinfo",
  "GET /api/cron/grant-cycle-post",
  "GET /api/cron/poll-conversions",
  "GET /api/cron/credits-expire-holds",
  "GET /api/cron/credits-expire-orders",
  "GET /api/cron/credits-plan-renewals",
  "GET /api/cron/credits-expire-lots",
  "GET /api/cron/credits-reconcile",
] as const;

// 시스템/내부 라우트: 세션·회사 접근 정책이 아니라 서버 간 공유 시크릿(INTERNAL_API_SECRET)으로
// 보호된다(authorizeInternalRequest). admin(apps/admin) 서버만 x-internal-secret 헤더로 호출한다
// (설계 9.3 "admin 결제 실행 경로"). 웹훅(/api/webhooks/*)과 같은 인증 클래스로, verify:route-policy
// 스코프(api/web, api/app/v1)와 크론 스코프(api/cron) 어디에도 속하지 않으므로 이 목록은 문서화·추적용이다.
// 미설정 시 INTERNAL_API_SECRET 부재로 401 을 반환해 사실상 비활성(공개 노출 없음).
export const SYSTEM_INTERNAL_ROUTES = [
  "POST /api/internal/credits/orders/[orderId]/sync",
  "POST /api/internal/credits/refunds/preview",
  "POST /api/internal/credits/refunds",
  "POST /api/internal/credits/subscriptions/[id]/force-cancel",
  "POST /api/internal/credits/subscriptions/cancel-schedules-for-user",
] as const;

export const SESSION_APP_ROUTES = [
  "GET /api/app/v1/companies",
  "POST /api/app/v1/companies",
  "GET /api/app/v1/companies/[companyId]/action-queue",
  "GET /api/app/v1/companies/[companyId]/consents",
  "PUT /api/app/v1/companies/[companyId]/consents",
  "DELETE /api/app/v1/companies/[companyId]/consents/[scope]",
  "POST /api/app/v1/companies/[companyId]/enrich",
  "GET /api/app/v1/companies/[companyId]/profile",
  "POST /api/app/v1/companies/[companyId]/profile/field",
  "POST /api/app/v1/companies/[companyId]/profile/fields",
  "POST /api/app/v1/companies/[companyId]/verify",
  "GET /api/app/v1/companies/[companyId]/matches",
  "GET /api/app/v1/companies/[companyId]/next-question",
  "GET /api/app/v1/companies/[companyId]/notifications",
  "POST /api/app/v1/companies/[companyId]/notifications/receipt",
  "GET /api/app/v1/companies/[companyId]/roadmap",
  "GET /api/app/v1/grants/[grantId]",
  "POST /api/app/v1/matches/[companyId]/[grantId]/feedback",
  "POST /api/app/v1/matches/[companyId]/[grantId]/events",
  "GET /api/app/v1/notifications/settings",
  "PUT /api/app/v1/notifications/settings",
  "POST /api/app/v1/devices",
  "DELETE /api/app/v1/devices/[deviceId]",
] as const;
