import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {tmpdir} from 'node:os';
import {createServer} from 'node:http';
const root=resolve(new URL('../..',import.meta.url).pathname), out=join(root,'docs/evidence/company-aware-design-20261001');
const req=createRequire(join(root,'apps/web/package.json')), esbuild=createRequire(createRequire(import.meta.url).resolve('tsx/package.json'))('esbuild');
const bundleRoot=mkdtempSync(join(tmpdir(),'company-design-'));
const exec=promisify(execFile), session='company-design-'+process.pid;
const browser=async(args,input)=>{if(input){const p=execFile('agent-browser',['--session',session,...args],{maxBuffer:20e6,timeout:30000});p.stdin.end(input); return await new Promise((res,rej)=>{let s='',e='';p.stdout.on('data',v=>s+=v);p.stderr.on('data',v=>e+=v);p.on('close',c=>c?rej(Error(e||s)):res(s));});}return (await exec('agent-browser',['--session',session,...args],{maxBuffer:20e6,timeout:30000})).stdout;};
const evaluate=async(code)=>{const value=JSON.parse(await browser(['eval','--stdin'],code));return value;};
mkdirSync(out,{recursive:true});
await esbuild.build({entryPoints:[join(root,'tools/design-company-review/entry.tsx')],bundle:true,platform:'browser',format:'iife',outfile:join(bundleRoot,'fixture.js'),tsconfig:join(root,'apps/web/tsconfig.json'),jsx:'automatic',define:{'process.env.NODE_ENV':'"development"'},nodePaths:[join(root,'apps/web/node_modules')],alias:{'@cunote/core':join(root,'tools/design-company-review/core.ts'),'next/navigation':join(root,'tools/design-company-review/navigation.ts')}});
const css=await req('postcss')([req('@tailwindcss/postcss')({base:join(root,'apps/web')})]).process(readFileSync(join(root,'apps/web/src/app/globals.css'),'utf8'),{from:join(root,'apps/web/src/app/globals.css')});
writeFileSync(join(bundleRoot,'fixture.css'),css.css);
const server=createServer((request,response)=>{const file=request.url?.split('?')[0];response.setHeader('content-type',file==='/fixture.js'?'text/javascript; charset=utf-8':file==='/fixture.css'?'text/css; charset=utf-8':'text/html; charset=utf-8');response.end(file==='/fixture.js'||file==='/fixture.css'?readFileSync(join(bundleRoot,file.slice(1))):'<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/fixture.css"><div id="root"></div><script>window.process={env:{NODE_ENV:"development"}};window.errors=[];window.addEventListener("error",e=>window.errors.push(e.message))</script><script src="/fixture.js"></script></html>');});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url='http://127.0.0.1:'+server.address().port+'/?companyId=company-A';
const sourceSha=(await exec('git',['rev-parse','HEAD'],{cwd:root})).stdout.trim();
const sourceDiff=(await exec('git',['diff','--','apps/web/src'],{cwd:root,maxBuffer:20e6})).stdout;
const report={sourceSha,sourceDiffSha256:createHash('sha256').update(sourceDiff).digest('hex'),fixture:true,externalWrites:0,actualSourceComponents:true,checks:[],screenshots:[]};
try{
 await browser(['open',url]); await browser(['wait','500']); await browser(['wait','--fn',"document.body.textContent.includes('합성 테스트 바톤')"]);
 for(const width of [1440,390,360]){await browser(['set','viewport',String(width),'1100']);for(const scene of ['explore','detail','writing','applications','workspace']){await evaluate(`(()=>{[...document.querySelectorAll('nav button')].find(b=>b.textContent==='${scene}').click();return true})()`);await browser(['wait','250']);const shot=`${scene}-${width}.png`;await browser(['screenshot',join(out,shot),'--full']);report.screenshots.push(shot);const layout=await evaluate(`({width:innerWidth,body:document.body.scrollWidth,text:document.body.textContent})`);if(layout.body>width+1)throw Error(scene+' overflow '+width+' actual '+layout.body);report.checks.push(scene+' layout '+width);}}
 await evaluate(`(()=>{[...document.querySelectorAll('nav button')].find(b=>b.textContent==='explore').click();return true})()`);
 await browser(['wait','100']);await evaluate(`(()=>{[...document.querySelectorAll('nav button')].find(b=>b.textContent==='회사 전환').click();return true})()`);await browser(['wait','100']);const b=await evaluate(`({text:document.body.textContent})`);if(b.text.includes('합성 테스트 바톤')||!b.text.includes('서울특별시'))throw Error('Company A leakage');report.checks.push('company A to B values replaced');
 for(const mode of ['partial','disputed','unknown','zero']){await evaluate(`(()=>{[...document.querySelectorAll('nav button')].find(b=>b.textContent==='${mode}').click();return true})()`);await browser(['wait','100']);if(mode==='partial'||mode==='disputed')await evaluate(`(()=>{document.querySelectorAll('main details').forEach(d=>d.open=true);return true})()`);const text=await evaluate('document.body.textContent');if(mode==='disputed'&&!text.includes('출처 충돌'))throw Error('Missing disputed fact');if(mode==='unknown'&&text.includes('소프트웨어 개발'))throw Error('Unknown fixture exposes known value');if(mode==='zero'&&!text.includes('아직 대조하지 못했어요'))throw Error('Discovery explanation missing');report.checks.push(mode+' profile/discovery state inspected');await browser(['screenshot',join(out,`explore-${mode}-360.png`),'--full']);report.screenshots.push(`explore-${mode}-360.png`);}

 const click=async(label)=>{await evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(label)});if(!b)throw Error('Missing button '+${JSON.stringify(label)});b.click();return true})()`);await browser(['wait','150']);};
 await click('writing');await browser(['wait','#writing-section-text']);
 await browser(['fill','#writing-section-text','수정한 사업 개요 문안 · 합성 검증']);await click('문안 저장');
 let state=await evaluate(`({text:document.querySelector('#writing-section-text').value,body:document.body.textContent})`);
 if(!state.body.includes('문안을 저장했어요')||state.text!=='수정한 사업 개요 문안 · 합성 검증')throw Error('Manual save failed');report.checks.push('manual edit and exact PUT save');
 await click('저장 문안과 양식 비교');await click('이 칸에 반영');
 if((await evaluate(`window.designAudit.applied.length`))!==1)throw Error('Safe saved text apply missing');report.checks.push('saved text comparison and binding callback apply');
 await evaluate(`(()=>{window.designAudit.conflict=true;return true})()`);await browser(['fill','#writing-section-text','409 후 보존할 입력']);await click('문안 저장');
 if(await evaluate(`document.querySelector('#writing-section-text').value`)!=='409 후 보존할 입력')throw Error('Conflict discarded input');
 if(!(await evaluate(`document.body.textContent`)).includes('다른 창에서 저장'))throw Error('Conflict message missing');report.checks.push('409 retains current input and shows recovery');await click('최신 저장본·결과 확인');await click('현재 입력 유지하고 저장 기준 갱신');await evaluate(`(()=>{window.designAudit.conflict=false;return true})()`);await click('문안 저장');if(!(await evaluate('document.body.textContent')).includes('문안을 저장했어요'))throw Error('Conflict recovery save failed');report.checks.push('409 compare preserve and retry save');
 await browser(['screenshot',join(out,'writing-recovered-360.png'),'--full']);report.screenshots.push('writing-recovered-360.png');
 await click('viewer');await browser(['wait','#writing-section-text']);if(!(await evaluate(`document.querySelector('#writing-section-text').disabled`)))throw Error('Viewer editor enabled');report.checks.push('viewer read-only text and copy access');
 await click('applications');const links=await evaluate(`[...document.querySelectorAll('main a')].map(a=>({text:a.textContent,href:a.getAttribute('href')}))`);if(!links.some(a=>a.text==='저장본 열기'&&a.href.includes('/workspace')))throw Error('Closed draft inaccessible');report.checks.push('closed draft reopen accessible on 360');
 await click('detail');const detail=await evaluate(`({text:document.body.textContent,hrefs:[...document.querySelectorAll('main a')].map(a=>a.getAttribute('href'))})`);if(!detail.text.includes('문서 열기')||!detail.text.includes('내 사업자 정보')||!detail.hrefs.some(h=>h.includes('companyId=company-B')))throw Error('Detail company and draft context missing');report.checks.push('detail source condition values and company-scoped saved draft CTA');
 await click('failed');await click('detail');await browser(['set','viewport','390','1100']);const failed=await evaluate(`({text:document.body.textContent,links:[...document.querySelectorAll('main a')].map(a=>({text:a.textContent.trim(),href:a.getAttribute('href')}))})`);if(!failed.text.includes('중요 자격 쟁점')||!failed.text.includes('서울특별시')||!failed.links.some(a=>a.text==='문서 열기'&&a.href.includes('companyId=company-B')))throw Error('Failed eligibility hides saved draft access or evidence');report.checks.push('failed eligibility issue and exact company saved draft CTA coexist');await browser(['screenshot',join(out,'detail-failed-saved-390.png'),'--full']);report.screenshots.push('detail-failed-saved-390.png');await browser(['set','viewport','360','1100']);
 await evaluate(`(()=>{window.designAudit.delayRead=true;return true})()`);await click('writing');await click('회사 전환');await browser(['wait','650']);if(await evaluate(`document.querySelector('#writing-section-text').value`)==='409 후 보존할 입력')throw Error('Late company B response leaked to A');report.checks.push('late prior-company GET does not replace current company editor');await evaluate(`(()=>{window.designAudit.delayRead=false;return true})()`);
 await click('workspace');await browser(['wait','#writing-section-text']);await browser(['fill','#writing-section-text','원본 탭을 오가도 유지할 문안']);await click('원본 양식');await click('문항 작성');if(await evaluate(`document.querySelector('#writing-section-text').value`)!=='원본 탭을 오가도 유지할 문안')throw Error('Mobile tab lost dirty input');report.checks.push('actual WorkspaceView mobile tab preserves dirty editor mount');
 report.originalDocumentBoundary='Actual WorkspaceView and RhwpStudioSurface rendered, synthetic API deliberately returns source unavailable; no original HWPX edit/download runtime acceptance claimed';
 const errors=await evaluate('window.errors');if(errors.length)throw Error('Browser runtime errors: '+errors.join(';'));report.checks.push('no browser runtime errors');
 report.audit=await evaluate(`window.designAudit`);report.ok=true;
}catch(error){report.ok=false;report.error=String(error);throw error;}finally{writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2));await browser(['close']).catch(()=>{});await new Promise(r=>server.close(r));rmSync(bundleRoot,{recursive:true,force:true});}
console.log(JSON.stringify(report));
