import { CRITERION_DIMENSIONS, GRANT_AUDIENCES, MATCH_REVIEW_REASON_CODES } from "./enums.js";

// 계약 단일 원천에서 파생한 enum 목록(복제 제거, M2). 순서는 CRITERION_DIMENSIONS/
// MATCH_REVIEW_REASON_CODES 배열과 항상 일치한다.
const CRITERION_DIMENSION_ENUM = [...CRITERION_DIMENSIONS];
const MATCH_REVIEW_REASON_CODE_ENUM = [...MATCH_REVIEW_REASON_CODES];
const GRANT_AUDIENCE_ENUM = [...GRANT_AUDIENCES];

const json = (schema: unknown) => ({
  "application/json": { schema },
});

const ref = (name: string) => ({
  $ref: `#/components/schemas/${name}`,
});

const arrayOf = (items: unknown) => ({
  type: "array",
  items,
});

const nullable = (schema: unknown) => ({
  anyOf: [schema, { type: "null" }],
});

const envelope = (data: unknown) => ({
  type: "object",
  required: ["data"],
  properties: {
    data,
    meta: ref("ApiMeta"),
    error: ref("ApiError"),
  },
  additionalProperties: false,
});

const pathParam = (name: string, description: string) => ({
  name,
  in: "path",
  required: true,
  description,
  schema: { type: "string" },
});

const queryParam = (name: string, description: string) => ({
  name,
  in: "query",
  required: false,
  description,
  schema: { type: "string" },
});

const bearerSecurity = [{ appBearerAuth: [] }];

export const appV1OpenApiRoutePaths = [
  "/api/app/v1/auth/{provider}",
  "/api/app/v1/auth/login",
  "/api/app/v1/auth/logout",
  "/api/app/v1/auth/refresh",
  "/api/app/v1/companies",
  "/api/app/v1/companies/{companyId}/action-queue",
  "/api/app/v1/companies/{companyId}/consents",
  "/api/app/v1/companies/{companyId}/consents/{scope}",
  "/api/app/v1/companies/{companyId}/enrich",
  "/api/app/v1/companies/{companyId}/matches",
  "/api/app/v1/companies/{companyId}/next-question",
  "/api/app/v1/companies/{companyId}/notifications",
  "/api/app/v1/companies/{companyId}/notifications/receipt",
  "/api/app/v1/companies/{companyId}/profile",
  "/api/app/v1/companies/{companyId}/profile/field",
  "/api/app/v1/companies/{companyId}/profile/fields",
  "/api/app/v1/companies/{companyId}/roadmap",
  "/api/app/v1/companies/{companyId}/verify",
  "/api/app/v1/devices",
  "/api/app/v1/devices/{deviceId}",
  "/api/app/v1/grants/{grantId}",
  "/api/app/v1/matches/{companyId}/{grantId}/events",
  "/api/app/v1/matches/{companyId}/{grantId}/feedback",
  "/api/app/v1/notifications/settings",
  "/api/app/v1/openapi.json",
  "/api/app/v1/stats",
  "/api/app/v1/teaser",
] as const;

export const appV1OpenApi = {
  openapi: "3.1.0",
  info: {
    title: "Changup Note App API",
    version: "1.0.0",
    description:
      "Versioned mobile API contract owned by cunote-web. Flutter clients should generate code from this document.",
  },
  servers: [
    {
      url: "https://dev.changupnote.com",
      description: "Development tunnel",
    },
    {
      url: "http://127.0.0.1:4010",
      description: "Local development",
    },
  ],
  tags: [
    { name: "System" },
    { name: "Auth" },
    { name: "Discovery" },
    { name: "Companies" },
    { name: "Consents" },
    { name: "Grants" },
    { name: "Matches" },
    { name: "Devices" },
    { name: "Notifications" },
  ],
  paths: {
    "/api/app/v1/openapi.json": {
      get: {
        tags: ["System"],
        operationId: "getAppV1OpenApi",
        summary: "Fetch the app v1 OpenAPI contract.",
        responses: {
          "200": {
            description: "OpenAPI contract.",
            content: json({ type: "object", additionalProperties: true }),
          },
        },
      },
    },
    "/api/app/v1/stats": {
      get: {
        tags: ["Discovery"],
        operationId: "getAppStats",
        summary: "Fetch public grant aggregate statistics.",
        responses: {
          "200": {
            description: "Current public aggregate statistics.",
            content: json(ref("StatsEnvelope")),
          },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/teaser": {
      post: {
        tags: ["Discovery"],
        operationId: "createAppTeaser",
        summary: "Create an anonymous first-pass match teaser.",
        requestBody: {
          required: false,
          content: json(ref("TeaserRequest")),
        },
        responses: {
          "200": {
            description: "Anonymous teaser result.",
            content: json(ref("ProductTeaserEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/auth/login": {
      post: {
        tags: ["Auth"],
        operationId: "loginAppUser",
        summary: "Exchange email credentials for app access and refresh tokens.",
        requestBody: {
          required: true,
          content: json(ref("LoginRequest")),
        },
        responses: {
          "200": {
            description: "Issued token pair.",
            content: json(ref("AppTokenEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "501": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/auth/refresh": {
      post: {
        tags: ["Auth"],
        operationId: "refreshAppToken",
        summary: "Rotate a refresh token and issue a new app token pair.",
        requestBody: {
          required: true,
          content: json(ref("RefreshRequest")),
        },
        responses: {
          "200": {
            description: "Rotated token pair.",
            content: json(ref("AppTokenEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/auth/logout": {
      post: {
        tags: ["Auth"],
        operationId: "logoutAppUser",
        summary: "Revoke a refresh token or all tokens for the current device.",
        security: [{ appBearerAuth: [] }, {}],
        requestBody: {
          required: true,
          content: json(ref("LogoutRequest")),
        },
        responses: {
          "200": {
            description: "Revocation result.",
            content: json(ref("LogoutEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/auth/{provider}": {
      post: {
        tags: ["Auth"],
        operationId: "exchangeAppOAuthCode",
        summary: "Exchange a native OAuth code for app tokens.",
        parameters: [pathParam("provider", "OAuth provider, for example google or kakao.")],
        requestBody: {
          required: true,
          content: json(ref("OAuthCodeExchangeRequest")),
        },
        responses: {
          "200": {
            description: "Issued token pair.",
            content: json(ref("AppTokenEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "501": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies": {
      get: {
        tags: ["Companies"],
        operationId: "listAppCompanies",
        summary: "List companies available to the current app user.",
        security: bearerSecurity,
        responses: {
          "200": {
            description: "Company list.",
            content: json(ref("CompanyListEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
      post: {
        tags: ["Companies"],
        operationId: "createAppCompany",
        summary: "Create or save the current user's company profile.",
        security: bearerSecurity,
        requestBody: {
          required: false,
          content: json(ref("CreateCompanyRequest")),
        },
        responses: {
          "201": {
            description: "Created company.",
            content: json(ref("CompanyEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/action-queue": {
      get: {
        tags: ["Matches"],
        operationId: "listAppCompanyActionQueue",
        summary: "Fetch ranked next actions for a company.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        responses: {
          "200": {
            description: "Ranked action queue.",
            content: json(ref("ActionQueueEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          "403": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/profile": {
      get: {
        tags: ["Companies"],
        operationId: "getAppCompanyProfile",
        summary: "Fetch a company profile.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        responses: {
          "200": {
            description: "Company profile.",
            content: json(ref("CompanyProfileEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          "404": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/enrich": {
      post: {
        tags: ["Companies"],
        operationId: "enrichAppCompany",
        summary: "Enrich a company profile from a business registration number.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        requestBody: {
          required: true,
          content: json(ref("CompanyEnrichmentRequest")),
        },
        responses: {
          "200": {
            description: "Enriched company profile and non-PII provider facts.",
            content: json(ref("CompanyEnrichmentEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "401": { $ref: "#/components/responses/AppError" },
          "403": { $ref: "#/components/responses/AppError" },
          "404": { $ref: "#/components/responses/AppError" },
          "502": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/verify": {
      post: {
        tags: ["Companies"],
        operationId: "verifyAppCompanyOwnership",
        summary: "Verify company ownership with business-registration facts.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        requestBody: {
          required: true,
          content: json(ref("CompanyVerificationRequest")),
        },
        responses: {
          "200": {
            description: "Verification result.",
            content: json(ref("CompanyVerificationEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "401": { $ref: "#/components/responses/AppError" },
          "403": { $ref: "#/components/responses/AppError" },
          "501": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/consents": {
      get: {
        tags: ["Consents"],
        operationId: "listAppCompanyConsents",
        summary: "List the current user's consent ledger entries for a company.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        responses: {
          "200": {
            description: "Consent list.",
            content: json(ref("ConsentListEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          "403": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
      put: {
        tags: ["Consents"],
        operationId: "grantAppCompanyConsent",
        summary: "Grant or refresh consent for a company data scope.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        requestBody: {
          required: true,
          content: json(ref("ConsentGrantRequest")),
        },
        responses: {
          "200": {
            description: "Stored consent.",
            content: json(ref("ConsentGrantEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "401": { $ref: "#/components/responses/AppError" },
          "403": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/consents/{scope}": {
      delete: {
        tags: ["Consents"],
        operationId: "revokeAppCompanyConsent",
        summary: "Revoke consent for a company data scope.",
        security: bearerSecurity,
        parameters: [
          pathParam("companyId", "Company id."),
          pathParam("scope", "Consent scope."),
        ],
        responses: {
          "200": {
            description: "Revocation result.",
            content: json(ref("ConsentRevokeEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "401": { $ref: "#/components/responses/AppError" },
          "403": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/profile/field": {
      post: {
        tags: ["Companies"],
        operationId: "updateAppCompanyProfileField",
        summary: "Persist a progressive profile-field answer.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        requestBody: {
          required: true,
          content: json(ref("ProfileFieldUpdateRequest")),
        },
        responses: {
          "200": {
            description: "Updated company profile.",
            content: json(ref("CompanyProfileUpdateEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "401": { $ref: "#/components/responses/AppError" },
          "404": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/profile/fields": {
      post: {
        tags: ["Companies"],
        operationId: "updateAppCompanyProfileFields",
        summary: "Persist a progressive profile-field answer.",
        description: "Plural path alias for mobile clients. The request currently updates one profile field per call.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        requestBody: {
          required: true,
          content: json(ref("ProfileFieldUpdateRequest")),
        },
        responses: {
          "200": {
            description: "Updated company profile.",
            content: json(ref("CompanyProfileUpdateEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "401": { $ref: "#/components/responses/AppError" },
          "404": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/matches": {
      get: {
        tags: ["Matches"],
        operationId: "listAppCompanyMatches",
        summary: "Fetch opportunity-map match cards for a company.",
        security: bearerSecurity,
        parameters: [
          pathParam("companyId", "Company id."),
          {
            name: "status",
            in: "query",
            required: false,
            description: "Optional eligibility or opportunity bucket filter.",
            schema: {
              type: "string",
              enum: ["all", "eligible", "conditional", "ineligible", "now", "soon", "preparable"],
            },
          },
          {
            name: "sort",
            in: "query",
            required: false,
            description: "Optional match sort order.",
            schema: {
              type: "string",
              enum: ["recommended", "fit", "deadline", "amount"],
            },
          },
          queryParam("cursor", "Opaque pagination cursor from the previous response meta."),
          {
            name: "limit",
            in: "query",
            required: false,
            description: "Page size, 1 through 40.",
            schema: { type: "integer", minimum: 1, maximum: 40 },
          },
        ],
        responses: {
          "200": {
            description: "Match cards and counts.",
            content: json(ref("CompanyMatchesEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/next-question": {
      get: {
        tags: ["Matches"],
        operationId: "getAppCompanyNextQuestion",
        summary: "Fetch the highest-leverage progressive question.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        responses: {
          "200": {
            description: "Next question, or null when none is useful.",
            content: json(ref("NextQuestionEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/notifications": {
      get: {
        tags: ["Notifications"],
        operationId: "listAppCompanyNotifications",
        summary: "Fetch notification feed items derived from current matches.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        responses: {
          "200": {
            description: "Notification feed.",
            content: json(ref("NotificationFeedEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/notifications/receipt": {
      post: {
        tags: ["Notifications"],
        operationId: "updateAppCompanyNotificationReceipt",
        summary: "Mark a notification as read or dismissed for the current app user.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        requestBody: {
          required: true,
          content: json(ref("NotificationReceiptRequest")),
        },
        responses: {
          "200": {
            description: "Updated notification receipt.",
            content: json(ref("NotificationReceiptEnvelope")),
          },
          "400": { $ref: "#/components/responses/AppError" },
          "401": { $ref: "#/components/responses/AppError" },
          "404": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/companies/{companyId}/roadmap": {
      get: {
        tags: ["Matches"],
        operationId: "listAppCompanyRoadmap",
        summary: "Fetch future opportunity roadmap nodes.",
        security: bearerSecurity,
        parameters: [pathParam("companyId", "Company id.")],
        responses: {
          "200": {
            description: "Roadmap nodes.",
            content: json(ref("RoadmapEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/grants/{grantId}": {
      get: {
        tags: ["Grants"],
        operationId: "getAppGrantApplySheet",
        summary: "Fetch an application-prep sheet for a grant.",
        security: bearerSecurity,
        parameters: [
          pathParam("grantId", "Grant id."),
          queryParam("companyId", "Optional company id. When omitted, the first accessible company is used."),
        ],
        responses: {
          "200": {
            description: "Application-prep sheet.",
            content: json(ref("ApplySheetEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          "404": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/matches/{companyId}/{grantId}/feedback": {
      post: {
        tags: ["Matches"],
        operationId: "submitAppMatchFeedback",
        summary: "Save user feedback for a grant match.",
        security: bearerSecurity,
        parameters: [
          pathParam("companyId", "Company id."),
          pathParam("grantId", "Grant id."),
        ],
        requestBody: {
          required: false,
          content: json(ref("MatchFeedbackRequest")),
        },
        responses: {
          "202": {
            description: "Feedback accepted.",
            content: json(ref("FeedbackEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/matches/{companyId}/{grantId}/events": {
      post: {
        tags: ["Matches"],
        operationId: "recordAppMatchEvent",
        summary: "Record an app interaction with a grant match.",
        security: bearerSecurity,
        parameters: [
          pathParam("companyId", "Company id."),
          pathParam("grantId", "Grant id."),
        ],
        requestBody: {
          required: false,
          content: json(ref("MatchEventRequest")),
        },
        responses: {
          "202": {
            description: "Event accepted.",
            content: json(ref("MatchEventEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/notifications/settings": {
      get: {
        tags: ["Notifications"],
        operationId: "getAppNotificationSettings",
        summary: "Fetch notification settings.",
        security: bearerSecurity,
        responses: {
          "200": {
            description: "Notification settings.",
            content: json(ref("NotificationSettingsEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
      put: {
        tags: ["Notifications"],
        operationId: "updateAppNotificationSettings",
        summary: "Update notification settings.",
        security: bearerSecurity,
        requestBody: {
          required: true,
          content: json(ref("NotificationSettings")),
        },
        responses: {
          "200": {
            description: "Notification settings.",
            content: json(ref("NotificationSettingsEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/devices": {
      post: {
        tags: ["Devices"],
        operationId: "registerAppDevice",
        summary: "Register the current mobile device for push delivery.",
        security: bearerSecurity,
        requestBody: {
          required: true,
          content: json(ref("DeviceRegistrationRequest")),
        },
        responses: {
          "201": {
            description: "Registered device.",
            content: json(ref("DeviceEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
    "/api/app/v1/devices/{deviceId}": {
      delete: {
        tags: ["Devices"],
        operationId: "deleteAppDevice",
        summary: "Delete a registered mobile device.",
        security: bearerSecurity,
        parameters: [pathParam("deviceId", "Device id.")],
        responses: {
          "200": {
            description: "Deleted device.",
            content: json(ref("DeleteDeviceEnvelope")),
          },
          "401": { $ref: "#/components/responses/AppError" },
          default: { $ref: "#/components/responses/AppError" },
        },
      },
    },
  },
  components: {
    securitySchemes: {
      appBearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "JWT",
      },
    },
    responses: {
      AppError: {
        description: "App API error envelope.",
        content: json(envelope(nullable({ type: "object", additionalProperties: true }))),
      },
    },
    schemas: {
      ApiError: {
        type: "object",
        required: ["code", "message"],
        properties: {
          code: { type: "string" },
          message: { type: "string" },
          field: { type: "string" },
        },
        additionalProperties: false,
      },
      ApiMeta: {
        type: "object",
        properties: {
          cursor: nullable({ type: "string" }),
          hasMore: { type: "boolean" },
          rulesetVer: { type: "string" },
          scoringVer: { type: "string" },
        },
        additionalProperties: false,
      },
      StatsResult: {
        type: "object",
        required: ["openCount", "totalAmount", "deadlineSoonCount", "updatedAt"],
        properties: {
          openCount: { type: "integer", minimum: 0 },
          totalAmount: { type: "integer", minimum: 0 },
          deadlineSoonCount: { type: "integer", minimum: 0 },
          updatedAt: { type: "string", format: "date-time" },
        },
        additionalProperties: false,
      },
      StatsEnvelope: envelope(ref("StatsResult")),
      TeaserRequest: {
        type: "object",
        properties: {
          bizNo: { type: "string" },
          answers: arrayOf(ref("MatchingProfileAnswerRequest")),
          profile: ref("CompanyProfile"),
        },
        additionalProperties: false,
      },
      MatchingProfileAnswerRequest: {
        type: "object",
        required: ["field"],
        properties: {
          field: { type: "string", enum: CRITERION_DIMENSION_ENUM },
          value: {},
          mode: { type: "string", enum: ["replace", "merge"] },
          unknown: { type: "boolean" },
          range: ref("MatchingProfileAnswerRange"),
        },
        additionalProperties: false,
      },
      MatchingProfileAnswerRange: {
        type: "object",
        required: ["min", "max", "unit"],
        properties: {
          min: { type: "number", minimum: 0 },
          max: nullable({ type: "number", minimum: 0 }),
          unit: { type: "string", enum: ["krw", "people"] },
        },
        additionalProperties: false,
      },
      TeaserResult: {
        type: "object",
        required: [
          "attributes",
          "estimatedMaxAmount",
          "conditionalUpside",
          "counts",
          "matches",
          "nextQuestion",
          "privacyNote",
        ],
        properties: {
          attributes: ref("TeaserAttributes"),
          estimatedMaxAmount: { type: "integer", minimum: 0 },
          conditionalUpside: { type: "integer", minimum: 0 },
          counts: ref("EligibilityCounts"),
          matches: arrayOf(ref("MatchCard")),
          nextQuestion: nullable(ref("NextQuestion")),
          recommendableMatches: arrayOf(ref("MatchCard")),
          reviewNeededMatches: arrayOf(ref("MatchCard")),
          searchContext: ref("TeaserSearchContext"),
          privacyNote: { type: "string" },
          companyEvidence: nullable(ref("CompanyEvidence")),
        },
        additionalProperties: false,
      },
      TeaserEnvelope: envelope(ref("TeaserResult")),
      ProductTeaserResult: {
        allOf: [
          ref("TeaserResult"),
          {
            type: "object",
            required: ["profileView"],
            properties: { profileView: ref("MatchingProfileView") },
          },
        ],
      },
      ProductTeaserEnvelope: envelope(ref("ProductTeaserResult")),
      MatchingProfileView: {
        type: "object",
        required: ["asOf", "knownCount", "partialCount", "unknownCount", "rows"],
        properties: {
          asOf: { type: "string", format: "date-time" },
          knownCount: { type: "integer", minimum: 0 },
          partialCount: { type: "integer", minimum: 0 },
          unknownCount: { type: "integer", minimum: 0 },
          rows: arrayOf(ref("MatchingProfileViewRow")),
        },
        additionalProperties: false,
      },
      MatchingProfileViewRow: {
        type: "object",
        required: [
          "dimension",
          "status",
          "displayValue",
          "sourceKind",
          "sourceLabel",
          "asOf",
          "completeness",
          "editMode",
          "action",
        ],
        properties: {
          dimension: { type: "string", enum: CRITERION_DIMENSION_ENUM },
          status: { type: "string", enum: ["known", "partial", "unknown"] },
          displayValue: nullable({ type: "string" }),
          sourceKind: nullable({
            type: "string",
            enum: ["authoritative_api", "public_registry", "auth_supplied", "self_declared", "derived"],
          }),
          sourceLabel: nullable({ type: "string" }),
          asOf: nullable({ type: "string", format: "date-time" }),
          completeness: nullable({ type: "string", enum: ["complete", "partial", "not_covered"] }),
          editMode: { type: "string", enum: ["direct", "question_only", "read_only"] },
          action: {
            type: "object",
            required: ["kind", "label"],
            properties: {
              kind: { type: "string", enum: ["answer", "connect", "refresh", "none"] },
              label: { type: "string" },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
      TeaserSearchContext: {
        type: "object",
        required: ["asOf", "evaluatedGrantCount", "lastCollectedAt"],
        properties: {
          asOf: { type: "string", format: "date-time" },
          evaluatedGrantCount: { type: "integer", minimum: 0 },
          lastCollectedAt: nullable({ type: "string", format: "date-time" }),
        },
        additionalProperties: false,
      },
      TeaserAttributes: {
        type: "object",
        required: ["region", "size", "bizAgeMonths", "industry"],
        properties: {
          region: nullable({ type: "string" }),
          size: nullable({ type: "string" }),
          bizAgeMonths: nullable({ type: "integer", minimum: 0 }),
          industry: arrayOf({ type: "string" }),
        },
        additionalProperties: false,
      },
      EligibilityCounts: {
        type: "object",
        required: ["eligible", "conditional", "ineligible", "deadlineSoon"],
        properties: {
          eligible: { type: "integer", minimum: 0 },
          conditional: { type: "integer", minimum: 0 },
          ineligible: { type: "integer", minimum: 0 },
          deadlineSoon: { type: "integer", minimum: 0 },
          recommendable: { type: "integer", minimum: 0 },
          reviewNeeded: { type: "integer", minimum: 0 },
          notRecommended: { type: "integer", minimum: 0 },
        },
        additionalProperties: false,
      },
      SupportAmount: {
        type: "object",
        required: ["unit", "per"],
        properties: {
          min: nullable({ type: "integer", minimum: 0 }),
          max: nullable({ type: "integer", minimum: 0 }),
          unit: { type: "string", enum: ["KRW"] },
          per: { type: "string", enum: ["기업", "건"] },
          label: nullable({ type: "string" }),
        },
        additionalProperties: false,
      },
      BenefitBadge: {
        type: "object",
        required: ["family", "label", "source", "confidence"],
        properties: {
          family: {
            type: "string",
            enum: ["funding", "loan", "capability", "space", "market", "certification", "network"],
          },
          label: { type: "string" },
          source: {
            type: "string",
            enum: ["structured", "support_amount", "title", "category", "apply_method"],
          },
          confidence: { type: "number", minimum: 0, maximum: 1 },
        },
        additionalProperties: false,
      },
      MatchCard: {
        type: "object",
        required: [
          "grantId",
          "source",
          "sourceId",
          "title",
          "agency",
          "status",
          "eligibility",
          "bucket",
          "fitScore",
          "supportAmount",
          "benefits",
          "applyEnd",
          "dDay",
          "ruleTrace",
          "matchConfidence",
          "rulesetVer",
          "scoringVer",
        ],
        properties: {
          grantId: { type: "string" },
          source: { type: "string", enum: ["kstartup", "bizinfo", "bizinfo_event"] },
          sourceId: { type: "string" },
          title: { type: "string" },
          agency: nullable({ type: "string" }),
          status: { type: "string", enum: ["upcoming", "open", "closed", "unknown"] },
          eligibility: { type: "string", enum: ["eligible", "conditional", "ineligible"] },
          bucket: { type: "string", enum: ["now", "soon", "preparable", "conditional"] },
          fitScore: { type: "number", minimum: 0, maximum: 100 },
          competitiveness: ref("EstimatedNumber"),
          value: { type: "integer", minimum: 0 },
          supportAmount: ref("SupportAmount"),
          benefits: arrayOf(ref("BenefitBadge")),
          applyEnd: nullable({ type: "string", format: "date" }),
          dDay: nullable({ type: "integer" }),
          ruleTrace: arrayOf(ref("RuleTraceChip")),
          matchConfidence: { type: "number", minimum: 0, maximum: 1 },
          rulesetVer: { type: "string" },
          scoringVer: { type: "string" },
          quality: ref("MatchQuality"),
          ranking: ref("MatchRanking"),
          criteriaExtracted: { type: "boolean" },
          recommendationTier: {
            type: "string",
            enum: ["recommendable", "needs_profile_input", "needs_core_review", "not_recommended"],
          },
          scoreDisplay: { type: "string", enum: ["numeric", "hidden"] },
          reviewReasons: arrayOf(ref("MatchReviewReason")),
          detailUrl: nullable({ type: "string" }),
        },
        additionalProperties: false,
      },
      MatchReviewReason: {
        type: "object",
        required: ["code", "dimension", "label"],
        properties: {
          code: {
            type: "string",
            enum: MATCH_REVIEW_REASON_CODE_ENUM,
          },
          dimension: {
            type: "string",
            enum: CRITERION_DIMENSION_ENUM,
          },
          label: { type: "string" },
          sourceSpan: { type: "string" },
        },
        additionalProperties: false,
      },
      MatchRanking: {
        type: "object",
        required: ["relevanceScore", "priorityScore", "reasons"],
        properties: {
          relevanceScore: nullable({ type: "number", minimum: 0, maximum: 100 }),
          priorityScore: nullable({ type: "number", minimum: 0, maximum: 100 }),
          reasons: arrayOf({ type: "string" }),
        },
        additionalProperties: false,
      },
      MatchQuality: {
        type: "object",
        required: [
          "eligibilityConfidence",
          "verificationCompleteness",
          "evidenceCoverage",
          "extractionReadiness",
        ],
        properties: {
          eligibilityConfidence: { type: "string", enum: ["high", "medium", "low"] },
          verificationCompleteness: { type: "number", minimum: 0, maximum: 100 },
          evidenceCoverage: { type: "number", minimum: 0, maximum: 100 },
          extractionReadiness: {
            type: "string",
            enum: ["reviewed", "structured_unreviewed", "partial", "unstructured"],
          },
        },
        additionalProperties: false,
      },
      EstimatedNumber: {
        type: "object",
        required: ["value", "estimated"],
        properties: {
          value: { type: "number" },
          estimated: { type: "boolean", const: true },
        },
        additionalProperties: false,
      },
      RuleTraceChip: {
        type: "object",
        required: ["dimension", "kind", "result", "label", "checklistSection"],
        properties: {
          dimension: {
            type: "string",
            enum: CRITERION_DIMENSION_ENUM,
          },
          kind: { type: "string", enum: ["required", "preferred", "exclusion"] },
          result: { type: "string", enum: ["pass", "fail", "unknown", "text_only"] },
          label: { type: "string" },
          companyValue: { type: "string" },
          sourceSpan: { type: "string" },
          checklistSection: {
            type: "string",
            enum: ["satisfied", "needs_check", "document", "preferred_miss"],
          },
          action: ref("RuleTraceAction"),
          unlock: ref("RuleTraceUnlock"),
        },
        additionalProperties: false,
      },
      RuleTraceAction: {
        type: "object",
        required: ["type", "target", "label"],
        properties: {
          type: {
            type: "string",
            enum: ["progressive", "external_link", "apply", "prepare", "verify"],
          },
          target: { type: "string" },
          label: { type: "string" },
        },
        additionalProperties: false,
      },
      RuleTraceUnlock: {
        type: "object",
        required: ["kind", "detail"],
        properties: {
          kind: { type: "string", enum: ["time", "attribute"] },
          detail: { type: "string" },
          etaDate: { type: "string", format: "date" },
        },
        additionalProperties: false,
      },
      RoadmapNode: {
        type: "object",
        required: ["bucket", "grantId", "title"],
        properties: {
          bucket: { type: "string", enum: ["now", "soon", "preparable", "conditional"] },
          grantId: { type: "string" },
          title: { type: "string" },
          unlock: ref("RoadmapUnlock"),
          deltaCount: { type: "integer" },
        },
        additionalProperties: false,
      },
      RoadmapUnlock: {
        type: "object",
        required: ["dimension", "kind", "detail"],
        properties: {
          dimension: { type: "string" },
          kind: { type: "string", enum: ["time", "attribute"] },
          detail: { type: "string" },
          etaDate: { type: "string", format: "date" },
        },
        additionalProperties: false,
      },
      NextQuestion: {
        type: "object",
        required: ["dimension", "definitionId", "prompt", "inputType", "preciseFollowUp", "framing", "affectedGrantCount"],
        properties: {
          dimension: { type: "string" },
          definitionId: { type: "string" },
          prompt: { type: "string" },
          inputType: { type: "string", enum: ["number", "select", "boolean", "text", "checklist", "number_group"] },
          options: arrayOf({ type: "string" }),
          unit: { type: "string", enum: ["krw", "people", "months", "years", "percent", "count"] },
          criterionThresholds: arrayOf({
            type: "object",
            required: ["field", "operator", "value", "unit", "affectedGrantCount"],
            properties: {
              field: { type: "string" },
              operator: { type: "string", enum: ["gt", "gte", "lt", "lte", "eq"] },
              value: { type: "number" },
              unit: nullable({ type: "string", enum: ["krw", "people", "months", "years", "percent", "count"] }),
              affectedGrantCount: { type: "integer", minimum: 0 },
            },
            additionalProperties: false,
          }),
          preciseFollowUp: { type: "string", enum: ["never", "when_range_straddles_threshold"] },
          responseStage: { type: "string", enum: ["direct", "range", "precise"] },
          rangeOptions: arrayOf({
            type: "object",
            required: ["value", "label", "min", "max", "unit"],
            properties: {
              value: { type: "string" },
              label: { type: "string" },
              min: { type: "number", minimum: 0 },
              max: nullable({ type: "number", minimum: 0 }),
              unit: { type: "string", enum: ["krw", "people"] },
            },
            additionalProperties: false,
          }),
          framing: { type: "string" },
          affectedGrantCount: { type: "integer", minimum: 0 },
          priorAwardContext: {
            type: "object",
            required: ["scope", "requiresYear"],
            properties: {
              scope: { type: "string", enum: ["self", "program", "program_type"] },
              selfKind: {
                type: "string",
                enum: ["current_similar", "same_project", "same_business_prior", "same_year_other_support"],
              },
              channel: { type: "string", enum: ["general", "incubation_tenancy"] },
              programs: arrayOf({ type: "string" }),
              states: arrayOf({ type: "string", enum: ["participating", "completed", "graduated"] }),
              requiresYear: { type: "boolean" },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
      ActionQueueItem: {
        type: "object",
        required: [
          "id",
          "kind",
          "title",
          "reason",
          "ctaLabel",
          "target",
          "affectedGrantIds",
          "affectedGrantCount",
          "leverageAmount",
          "urgency",
          "effort",
          "score",
        ],
        properties: {
          id: { type: "string" },
          kind: { type: "string", enum: ["input", "acquire", "apply", "enrich", "review"] },
          title: { type: "string" },
          reason: { type: "string" },
          ctaLabel: { type: "string" },
          target: { type: "string" },
          affectedGrantIds: arrayOf({ type: "string" }),
          affectedGrantCount: { type: "integer", minimum: 0 },
          leverageAmount: { type: "integer", minimum: 0 },
          urgency: { type: "string", enum: ["low", "medium", "high"] },
          effort: { type: "string", enum: ["quick", "medium", "long"] },
          score: { type: "number" },
        },
        additionalProperties: false,
      },
      ActionQueueResult: {
        type: "object",
        required: ["actions"],
        properties: {
          actions: arrayOf(ref("ActionQueueItem")),
        },
        additionalProperties: false,
      },
      GrantDetail: {
        type: "object",
        required: ["id", "source", "sourceId", "title", "agency", "supportAmount", "benefits", "status"],
        properties: {
          id: { type: "string" },
          source: { type: "string", enum: ["kstartup", "bizinfo", "bizinfo_event"] },
          sourceId: { type: "string" },
          title: { type: "string" },
          agency: nullable({ type: "string" }),
          supportAmount: ref("SupportAmount"),
          benefits: arrayOf(ref("BenefitBadge")),
          status: { type: "string", enum: ["upcoming", "open", "closed", "unknown"] },
          audience: { type: "string", enum: GRANT_AUDIENCE_ENUM },
        },
        additionalProperties: false,
      },
      RequiredDocument: {
        type: "object",
        required: ["name", "required", "source"],
        properties: {
          name: { type: "string" },
          required: { type: "boolean" },
          source: { type: "string", enum: ["self", "portal", "cert"] },
          category: {
            type: "string",
            enum: [
              "application_form",
              "business_plan",
              "proposal_or_intro",
              "consent_or_pledge",
              "business_registration",
              "corporate_register",
              "company_confirmation",
              "financial_tax",
              "employment_insurance",
              "shareholder",
              "bank_account",
              "estimate_budget",
              "portfolio_catalog",
              "ip_certification",
              "recommendation",
              "performance_evidence",
              "other",
            ],
          },
          preparationType: { type: "string", enum: ["write", "issue", "attach", "portal", "other"] },
          canonicalName: { type: "string" },
          templateRequired: { type: "boolean" },
          sourceAttachment: { type: "string" },
          alreadyHave: { type: "boolean" },
          fromTextOnly: { type: "boolean" },
          sourceSpan: { type: "string" },
          note: { type: "string" },
          confidence: { type: "number", minimum: 0, maximum: 1 },
        },
        additionalProperties: false,
      },
      SourceAttachment: {
        type: "object",
        required: ["filename", "url"],
        properties: {
          filename: { type: "string" },
          url: nullable({ type: "string" }),
          sourceUri: nullable({ type: "string" }),
          archiveUrl: nullable({ type: "string" }),
          markdownUrl: nullable({ type: "string" }),
        },
        additionalProperties: false,
      },
      MissingFieldQuestion: {
        type: "object",
        required: ["fieldKey", "label", "reason"],
        properties: {
          fieldKey: { type: "string" },
          label: { type: "string" },
          reason: { type: "string" },
          documentName: { type: "string" },
          category: {
            type: "string",
            enum: [
              "application_form",
              "business_plan",
              "proposal_or_intro",
              "consent_or_pledge",
              "business_registration",
              "corporate_register",
              "company_confirmation",
              "financial_tax",
              "employment_insurance",
              "shareholder",
              "bank_account",
              "estimate_budget",
              "portfolio_catalog",
              "ip_certification",
              "recommendation",
              "performance_evidence",
              "other",
            ],
          },
        },
        additionalProperties: false,
      },
      DocumentPreparationGroup: {
        type: "object",
        required: ["preparationType", "label", "description", "documents"],
        properties: {
          preparationType: { type: "string", enum: ["write", "issue", "attach", "portal", "other", "unknown"] },
          label: { type: "string" },
          description: { type: "string" },
          documents: arrayOf(ref("RequiredDocument")),
        },
        additionalProperties: false,
      },
      DraftableDocument: {
        type: "object",
        required: [
          "documentKey",
          "name",
          "category",
          "canonicalName",
          "sourceAttachment",
          "templateRequired",
          "confidence",
          "status",
          "hwpxTemplateAvailable",
        ],
        properties: {
          documentKey: { type: "string" },
          name: { type: "string" },
          category: {
            type: "string",
            enum: [
              "application_form",
              "business_plan",
              "proposal_or_intro",
              "consent_or_pledge",
              "business_registration",
              "corporate_register",
              "company_confirmation",
              "financial_tax",
              "employment_insurance",
              "shareholder",
              "bank_account",
              "estimate_budget",
              "portfolio_catalog",
              "ip_certification",
              "recommendation",
              "performance_evidence",
              "other",
            ],
          },
          canonicalName: { type: "string" },
          sourceAttachment: nullable({ type: "string" }),
          templateRequired: { type: "boolean" },
          confidence: nullable({ type: "number", minimum: 0, maximum: 1 }),
          status: { type: "string", enum: ["not_started", "draft_ready", "needs_user_input", "reviewed", "done"] },
          hwpxTemplateAvailable: { type: "boolean" },
        },
        additionalProperties: false,
      },
      DraftCoverage: {
        type: "object",
        required: [
          "totalDocuments",
          "draftableCount",
          "issuableCount",
          "attachableCount",
          "otherCount",
          "withAttachmentContextCount",
          "missingFieldCount",
        ],
        properties: {
          totalDocuments: { type: "integer", minimum: 0 },
          draftableCount: { type: "integer", minimum: 0 },
          issuableCount: { type: "integer", minimum: 0 },
          attachableCount: { type: "integer", minimum: 0 },
          otherCount: { type: "integer", minimum: 0 },
          withAttachmentContextCount: { type: "integer", minimum: 0 },
          missingFieldCount: { type: "integer", minimum: 0 },
        },
        additionalProperties: false,
      },
      ProfileCopyField: {
        type: "object",
        required: ["label", "value", "source"],
        properties: {
          label: { type: "string" },
          value: { type: "string" },
          source: { type: "string", enum: ["company_profile", "grant_context"] },
        },
        additionalProperties: false,
      },
      PlanDraftPrompt: {
        type: "object",
        required: ["title", "prompt", "evidence"],
        properties: {
          title: { type: "string" },
          prompt: { type: "string" },
          evidence: arrayOf({ type: "string" }),
        },
        additionalProperties: false,
      },
      ApplicationPrep: {
        type: "object",
        required: [
          "autoSubmitSupported",
          "profileCopyFields",
          "planDraftPrompts",
          "documentGroups",
          "draftableDocuments",
          "issuableDocuments",
          "attachableDocuments",
          "missingProfileFields",
          "draftCoverage",
        ],
        properties: {
          autoSubmitSupported: { type: "boolean", const: false },
          profileCopyFields: arrayOf(ref("ProfileCopyField")),
          planDraftPrompts: arrayOf(ref("PlanDraftPrompt")),
          documentGroups: arrayOf(ref("DocumentPreparationGroup")),
          draftableDocuments: arrayOf(ref("DraftableDocument")),
          issuableDocuments: arrayOf(ref("RequiredDocument")),
          attachableDocuments: arrayOf(ref("RequiredDocument")),
          missingProfileFields: arrayOf(ref("MissingFieldQuestion")),
          draftCoverage: ref("DraftCoverage"),
        },
        additionalProperties: false,
      },
      ApplySheet: {
        type: "object",
        required: [
          "grant",
          "satisfied",
          "needsCheck",
          "documents",
          "sourceAttachments",
          "applicationPrep",
          "applyMethod",
          "deepLink",
          "schedule",
        ],
        properties: {
          grant: ref("GrantDetail"),
          satisfied: arrayOf(ref("RuleTraceChip")),
          needsCheck: arrayOf(ref("RuleTraceChip")),
          documents: arrayOf(ref("RequiredDocument")),
          sourceAttachments: arrayOf(ref("SourceAttachment")),
          applicationPrep: ref("ApplicationPrep"),
          applyMethod: nullable({ type: "string" }),
          deepLink: nullable({ type: "string" }),
          schedule: ref("ApplySchedule"),
        },
        additionalProperties: false,
      },
      ApplySchedule: {
        type: "object",
        required: ["applyStart", "applyEnd", "dDay"],
        properties: {
          applyStart: nullable({ type: "string", format: "date" }),
          applyEnd: nullable({ type: "string", format: "date" }),
          dDay: nullable({ type: "integer" }),
        },
        additionalProperties: false,
      },
      CompanyProfile: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          region: ref("CompanyRegion"),
          biz_age_months: nullable({ type: "integer", minimum: 0 }),
          founder_age: nullable({ type: "integer", minimum: 0 }),
          is_preliminary: { type: "boolean" },
          industries: arrayOf({ type: "string" }),
          industry_codes: arrayOf({ type: "string" }),
          size: nullable({ type: "string" }),
          revenue_krw: nullable({ type: "number", minimum: 0 }),
          employees_count: nullable({ type: "integer", minimum: 0 }),
          traits: arrayOf({ type: "string" }),
          certs: arrayOf({ type: "string" }),
          prior_awards: arrayOf({ type: "string" }),
          prior_award_history: {
            type: "object",
            required: ["records", "known_programs", "known_program_types"],
            properties: {
              records: arrayOf({
                type: "object",
                required: ["state"],
                properties: {
                  program: { type: "string" },
                  agency: { type: "string" },
                  year: nullable({ type: "integer", minimum: 1900, maximum: 2100 }),
                  state: { type: "string", enum: ["participating", "completed", "graduated"] },
                },
                additionalProperties: false,
              }),
              self_flags: {
                type: "object",
                properties: {
                  current_similar: { type: "boolean" },
                  same_project: { type: "boolean" },
                  same_business_prior: { type: "boolean" },
                  same_year_other_support: { type: "boolean" },
                },
                additionalProperties: false,
              },
              has_incubation_tenancy: { type: "boolean" },
              known_programs: arrayOf({ type: "string" }),
              known_program_types: arrayOf({ type: "string" }),
            },
            additionalProperties: false,
          },
          ip: arrayOf({ type: "string" }),
          target_types: arrayOf({ type: "string" }),
          list_completeness: {
            type: "object",
            additionalProperties: { type: "string", enum: ["partial", "complete"] },
          },
          other_conditions: nullable({ type: "object", additionalProperties: true }),
          business_status: ref("CompanyBusinessStatus"),
          tax_compliance: ref("DisqualificationProfileValue"),
          credit_status: ref("DisqualificationProfileValue"),
          sanction: ref("DisqualificationProfileValue"),
          financial_health: ref("FinancialHealthProfileValue"),
          insured_workforce: ref("InsuredWorkforceProfileValue"),
          investment: ref("InvestmentProfileValue"),
          confidence: { type: "object", additionalProperties: { type: "number" } },
          profile_evidence: {
            type: "object",
            additionalProperties: ref("CompanyProfileFieldEvidence"),
          },
          question_answer_state: {
            type: "object",
            additionalProperties: ref("CompanyProfileQuestionAnswerState"),
          },
        },
        additionalProperties: true,
      },
      CompanyProfileFieldEvidence: {
        type: "object",
        required: ["sourceKind", "provider", "asOf", "axisCompleteness", "confidence"],
        properties: {
          sourceKind: {
            type: "string",
            enum: ["authoritative_api", "public_registry", "auth_supplied", "self_declared", "derived"],
          },
          provider: { type: "string" },
          asOf: nullable({ type: "string", format: "date-time" }),
          axisCompleteness: { type: "string", enum: ["partial", "complete"] },
          confidence: nullable({ type: "number", minimum: 0, maximum: 1 }),
          scope: { type: "string", enum: ["shared", "user"] },
          observationId: { type: "string", minLength: 1 },
          observationVersion: { type: "string", minLength: 1 },
          canonicalValue: { type: "string" },
          persistenceClass: {
            type: "string",
            enum: ["portable_user_answer", "versioned_provider_observation"],
          },
          resolverVersion: { type: "string", minLength: 1 },
          supplemental: arrayOf(ref("CompanyProfileEvidenceObservation")),
        },
        additionalProperties: false,
      },
      CompanyProfileEvidenceObservation: {
        type: "object",
        required: ["sourceKind", "provider", "asOf", "axisCompleteness", "confidence"],
        properties: {
          sourceKind: {
            type: "string",
            enum: ["authoritative_api", "public_registry", "auth_supplied", "self_declared", "derived"],
          },
          provider: { type: "string" },
          asOf: nullable({ type: "string", format: "date-time" }),
          axisCompleteness: { type: "string", enum: ["partial", "complete"] },
          confidence: nullable({ type: "number", minimum: 0, maximum: 1 }),
          scope: { type: "string", enum: ["shared", "user"] },
          observationId: { type: "string", minLength: 1 },
          observationVersion: { type: "string", minLength: 1 },
          canonicalValue: { type: "string" },
          persistenceClass: {
            type: "string",
            enum: ["portable_user_answer", "versioned_provider_observation"],
          },
          resolverVersion: { type: "string", minLength: 1 },
        },
        additionalProperties: false,
      },
      CompanyBusinessStatus: {
        type: "object",
        properties: {
          active: { type: "boolean" },
          close_down_state: nullable({ anyOf: [{ type: "string" }, { type: "number" }] }),
          close_down_tax_type: nullable({ anyOf: [{ type: "string" }, { type: "number" }] }),
          label: { type: "string" },
        },
        additionalProperties: false,
      },
      DisqualificationProfileValue: {
        type: "object",
        required: ["flags", "known_flags", "exceptions"],
        properties: {
          flags: arrayOf({ type: "string" }),
          known_flags: arrayOf({ type: "string" }),
          exceptions: arrayOf({ type: "string" }),
        },
        additionalProperties: false,
      },
      FinancialHealthProfileValue: {
        type: "object",
        properties: {
          debt_ratio_pct: nullable({ type: "number" }),
          impairment: nullable({ type: "string", enum: ["none", "partial", "full"] }),
          interest_coverage_ratio: nullable({ type: "number" }),
          total_assets_krw: nullable({ type: "number", minimum: 0 }),
          equity_krw: nullable({ type: "number" }),
          capital_krw: nullable({ type: "number", minimum: 0 }),
          fiscal_year: { type: "string" },
        },
        additionalProperties: false,
      },
      InsuredWorkforceProfileValue: {
        type: "object",
        properties: {
          employment_insurance_active: { type: "boolean" },
          insured_count: nullable({ type: "integer", minimum: 0 }),
          months_since_last_layoff: nullable({ type: "integer", minimum: 0 }),
          no_layoff: { type: "boolean" },
        },
        additionalProperties: false,
      },
      InvestmentProfileValue: {
        type: "object",
        properties: {
          total_raised_krw: nullable({ type: "number", minimum: 0 }),
          last_round: nullable({ type: "string" }),
          tips_backed: { type: "boolean" },
        },
        additionalProperties: false,
      },
      CompanyProfileQuestionAnswerState: {
        type: "object",
        required: ["status", "answeredAt", "expiresAt", "sourceKind", "rulesetVer"],
        properties: {
          status: { type: "string", enum: ["unknown", "range"] },
          answeredAt: { type: "string", format: "date-time" },
          expiresAt: { type: "string", format: "date-time" },
          sourceKind: { type: "string", enum: ["self_declared"] },
          rulesetVer: nullable({ type: "string" }),
          min: { type: "number", minimum: 0 },
          max: nullable({ type: "number", minimum: 0 }),
          unit: { type: "string", enum: ["krw", "people"] },
        },
        additionalProperties: false,
      },
      CompanyRegion: {
        type: "object",
        required: ["code"],
        properties: {
          code: { type: "string" },
          label: { type: "string" },
        },
        additionalProperties: false,
      },
      CompanyEnrichmentRequest: {
        type: "object",
        required: ["bizNo"],
        properties: {
          bizNo: { type: "string", minLength: 10 },
        },
        additionalProperties: false,
      },
      CompanyPreviewRequest: {
        type: "object",
        required: ["bizNo"],
        properties: {
          bizNo: { type: "string", minLength: 10 },
        },
        additionalProperties: false,
      },
      CompanyPreviewResult: {
        type: "object",
        required: ["name", "maskedBizNo"],
        properties: {
          name: nullable({ type: "string" }),
          maskedBizNo: { type: "string" },
          businessStatus: {
            type: "object",
            properties: {
              active: { type: "boolean" },
              label: { type: "string" },
            },
            additionalProperties: false,
          },
          regionLabel: { type: "string" },
          checkedAt: { type: "string" },
          cacheStatus: { type: "string" },
        },
        additionalProperties: false,
      },
      CompanyVerificationRequest: {
        type: "object",
        required: ["bizNo"],
        properties: {
          bizNo: { type: "string", minLength: 10 },
          ownerName: { type: "string" },
          openedOn: { type: "string", format: "date" },
        },
        additionalProperties: false,
      },
      CompanyVerificationResult: {
        type: "object",
        required: ["companyId", "bizNoMasked", "verified", "verifiedAt", "verifyMethod"],
        properties: {
          companyId: { type: "string" },
          bizNoMasked: { type: "string" },
          verified: { type: "boolean" },
          verifiedAt: { type: "string", format: "date-time" },
          verifyMethod: { type: "string" },
        },
        additionalProperties: false,
      },
      CompanyVerificationEnvelope: envelope(ref("CompanyVerificationResult")),
      CompanyEnrichmentFacts: {
        type: "object",
        required: [
          "maskedBizNo",
          "result",
          "resultMessage",
          "checkedAt",
          "hasCorpName",
          "hasRegion",
          "hasBizAge",
          "hasSize",
          "hasIndustry",
          "closeDownState",
          "closeDownTaxType",
        ],
        properties: {
          maskedBizNo: nullable({ type: "string" }),
          result: { anyOf: [{ type: "number" }, { type: "string" }, { type: "null" }] },
          resultMessage: nullable({ type: "string" }),
          checkedAt: nullable({ type: "string" }),
          hasCorpName: { type: "boolean" },
          hasRegion: { type: "boolean" },
          hasBizAge: { type: "boolean" },
          hasSize: { type: "boolean" },
          hasIndustry: { type: "boolean" },
          closeDownState: { anyOf: [{ type: "number" }, { type: "string" }, { type: "null" }] },
          closeDownTaxType: { anyOf: [{ type: "number" }, { type: "string" }, { type: "null" }] },
        },
        additionalProperties: false,
      },
      CompanyEvidenceField: {
        type: "object",
        required: ["key", "label", "available", "value"],
        properties: {
          key: { type: "string" },
          label: { type: "string" },
          available: { type: "boolean" },
          value: nullable({ type: "string" }),
        },
        additionalProperties: false,
      },
      CompanyEvidence: {
        type: "object",
        required: [
          "provider",
          "source",
          "cacheStatus",
          "checkedAt",
          "cachedUntil",
          "maskedBizNo",
          "resultMessage",
          "fields",
          "summary",
        ],
        properties: {
          provider: { type: "string", enum: ["popbill", "apick", "internal", "manual", "sample"] },
          source: {
            type: "string",
            enum: [
              "popbill_live",
              "popbill_cache",
              "apick_live",
              "apick_cache",
              "saved_profile",
              "manual_profile",
              "sample_profile",
            ],
          },
          cacheStatus: { type: "string", enum: ["hit", "stored", "none"] },
          checkedAt: nullable({ type: "string", format: "date-time" }),
          cachedUntil: nullable({ type: "string", format: "date-time" }),
          maskedBizNo: nullable({ type: "string" }),
          resultMessage: nullable({ type: "string" }),
          fields: arrayOf(ref("CompanyEvidenceField")),
          summary: { type: "string" },
        },
        additionalProperties: false,
      },
      CompanyEnrichmentResult: {
        type: "object",
        required: ["profile", "facts", "initialMatch"],
        properties: {
          profile: ref("CompanyProfile"),
          facts: ref("CompanyEnrichmentFacts"),
          evidence: nullable(ref("CompanyEvidence")),
          initialMatch: ref("CompanyInitialMatchResult"),
        },
        additionalProperties: false,
      },
      CompanyInitialMatchResult: {
        type: "object",
        required: [
          "asOf",
          "evaluatedGrantCount",
          "counts",
          "matches",
          "nextQuestion",
          "rulesetVer",
          "scoringVer",
        ],
        properties: {
          asOf: { type: "string", format: "date-time" },
          evaluatedGrantCount: { type: "integer", minimum: 0 },
          counts: ref("EligibilityCounts"),
          matches: arrayOf(ref("MatchCard")),
          nextQuestion: nullable(ref("NextQuestion")),
          rulesetVer: { type: "string" },
          scoringVer: { type: "string" },
        },
        additionalProperties: false,
      },
      CompanyRecord: {
        type: "object",
        required: ["id", "name", "profile"],
        properties: {
          id: { type: "string" },
          name: nullable({ type: "string" }),
          profile: ref("CompanyProfile"),
          role: { type: "string", enum: ["owner", "admin", "member", "viewer"] },
          verified: { type: "boolean" },
          verifiedAt: nullable({ type: "string", format: "date-time" }),
          verifyMethod: nullable({ type: "string" }),
          bizNoMasked: nullable({ type: "string" }),
        },
        additionalProperties: false,
      },
      CreateCompanyRequest: {
        type: "object",
        required: ["profile"],
        properties: {
          profile: ref("CompanyProfile"),
        },
        additionalProperties: false,
      },
      ProfileFieldUpdateRequest: {
        type: "object",
        required: ["field"],
        anyOf: [
          { required: ["value"] },
          { required: ["unknown"], properties: { unknown: { const: true } } },
          { required: ["range"] },
        ],
        properties: {
          field: {
            type: "string",
            enum: CRITERION_DIMENSION_ENUM,
          },
          value: {
            description: "Field-specific JSON value.",
          },
          confidence: nullable({ type: "number", minimum: 0, maximum: 1 }),
          mode: { type: "string", enum: ["replace", "merge"] },
          unknown: {
            type: "boolean",
            description: "True records a temporary unknown answer without writing a profile value.",
          },
          range: {
            type: "object",
            required: ["min", "max", "unit"],
            properties: {
              min: { type: "number", minimum: 0 },
              max: nullable({ type: "number", minimum: 0 }),
              unit: { type: "string", enum: ["krw", "people"] },
            },
            additionalProperties: false,
            description: "Self-declared revenue or employee interval. It resolves only criteria fully outside/inside the interval.",
          },
          questionSessionId: {
            type: "string",
            format: "uuid",
            description: "Optional 30-minute progressive-question session id. Invalid values are replaced server-side.",
          },
        },
        additionalProperties: false,
      },
      CompanyListResult: {
        type: "object",
        required: ["companies"],
        properties: {
          companies: arrayOf(ref("CompanyRecord")),
        },
        additionalProperties: false,
      },
      CompanyResult: {
        type: "object",
        required: ["company"],
        properties: {
          company: ref("CompanyRecord"),
        },
        additionalProperties: false,
      },
      CompanyProfileResult: {
        type: "object",
        required: ["profile"],
        properties: {
          profile: ref("CompanyProfile"),
        },
        additionalProperties: false,
      },
      ProfileUpdateImpact: {
        type: "object",
        required: [
          "scope",
          "windowLimit",
          "dimension",
          "evaluatedGrantCount",
          "targetedConditionalCount",
          "dimensionResolvedGrantCount",
          "eligibilityResolvedCount",
          "conditionalToEligibleCount",
          "conditionalToIneligibleCount",
          "remainingConditionalCount",
          "conditionalResolutionRate",
          "transitionCounts",
          "changedMatchStateCount",
          "refreshGrantIds",
        ],
        properties: {
          scope: { type: "string", enum: ["active_grant_window"] },
          windowLimit: { type: "integer", minimum: 0 },
          dimension: { type: "string", enum: CRITERION_DIMENSION_ENUM },
          evaluatedGrantCount: { type: "integer", minimum: 0 },
          targetedConditionalCount: { type: "integer", minimum: 0 },
          dimensionResolvedGrantCount: { type: "integer", minimum: 0 },
          eligibilityResolvedCount: { type: "integer", minimum: 0 },
          conditionalToEligibleCount: { type: "integer", minimum: 0 },
          conditionalToIneligibleCount: { type: "integer", minimum: 0 },
          remainingConditionalCount: { type: "integer", minimum: 0 },
          conditionalResolutionRate: nullable({ type: "number", minimum: 0, maximum: 1 }),
          transitionCounts: {
            type: "object",
            additionalProperties: { type: "integer", minimum: 0 },
          },
          changedMatchStateCount: { type: "integer", minimum: 0 },
          refreshGrantIds: arrayOf({ type: "string" }),
        },
        additionalProperties: false,
      },
      ProfileQuestionRefresh: {
        type: "object",
        required: ["scope", "status", "plannedCount", "savedCount", "failedCount", "failedGrantIds"],
        properties: {
          scope: { type: "string", enum: ["company_dimension"] },
          status: { type: "string", enum: ["no_op", "succeeded", "partial", "failed"] },
          plannedCount: { type: "integer", minimum: 0 },
          savedCount: { type: "integer", minimum: 0 },
          failedCount: { type: "integer", minimum: 0 },
          failedGrantIds: arrayOf({ type: "string" }),
        },
        additionalProperties: false,
      },
      CompanyProfileUpdateResult: {
        type: "object",
        required: ["profile", "impact", "refresh", "event", "initialMatch"],
        properties: {
          profile: ref("CompanyProfile"),
          impact: ref("ProfileUpdateImpact"),
          refresh: ref("ProfileQuestionRefresh"),
          event: ref("ProfileQuestionEventReceipt"),
          initialMatch: ref("CompanyInitialMatchResult"),
        },
        additionalProperties: false,
      },
      ProfileQuestionEventReceipt: {
        type: "object",
        required: ["id", "sessionId", "recordedAt", "persisted"],
        properties: {
          id: { type: "string" },
          sessionId: { type: "string", format: "uuid" },
          recordedAt: { type: "string", format: "date-time" },
          persisted: { type: "boolean" },
        },
        additionalProperties: false,
      },
      CompanyMatchesResult: {
        type: "object",
        required: ["counts", "matches", "profileView", "total"],
        properties: {
          counts: ref("EligibilityCounts"),
          matches: arrayOf(ref("MatchCard")),
          profileView: ref("MatchingProfileView"),
          total: { type: "integer", minimum: 0 },
        },
        additionalProperties: false,
      },
      RoadmapResult: {
        type: "object",
        required: ["roadmap"],
        properties: {
          roadmap: arrayOf(ref("RoadmapNode")),
        },
        additionalProperties: false,
      },
      LoginRequest: {
        type: "object",
        required: ["email"],
        properties: {
          email: { type: "string", format: "email" },
          password: { type: "string", format: "password" },
          deviceId: { type: "string" },
        },
        additionalProperties: false,
      },
      OAuthCodeExchangeRequest: {
        type: "object",
        required: ["code"],
        properties: {
          code: { type: "string" },
          codeVerifier: { type: "string" },
          redirectUri: { type: "string" },
          deviceId: { type: "string" },
        },
        additionalProperties: false,
      },
      RefreshRequest: {
        type: "object",
        required: ["refreshToken"],
        properties: {
          refreshToken: { type: "string" },
        },
        additionalProperties: false,
      },
      LogoutRequest: {
        type: "object",
        properties: {
          refreshToken: { type: "string" },
          allForDevice: { type: "boolean" },
        },
        additionalProperties: false,
      },
      AppTokenResponse: {
        type: "object",
        required: [
          "tokenType",
          "accessToken",
          "refreshToken",
          "expiresIn",
          "refreshExpiresAt",
          "deviceId",
          "user",
        ],
        properties: {
          tokenType: { type: "string", enum: ["Bearer"] },
          accessToken: { type: "string" },
          refreshToken: { type: "string" },
          expiresIn: { type: "integer", minimum: 0 },
          refreshExpiresAt: { type: "string", format: "date-time" },
          deviceId: { type: "string" },
          user: ref("AppTokenUser"),
        },
        additionalProperties: false,
      },
      AppTokenUser: {
        type: "object",
        required: ["id", "email"],
        properties: {
          id: { type: "string" },
          email: nullable({ type: "string", format: "email" }),
        },
        additionalProperties: false,
      },
      LogoutResult: {
        type: "object",
        required: ["revoked"],
        properties: {
          revoked: { type: "boolean" },
        },
        additionalProperties: false,
      },
      MatchFeedbackRequest: {
        type: "object",
        properties: {
          kind: {
            type: "string",
            enum: ["saved", "dismissed", "wrong", "applied", "selected", "rejected", "blocked", "note"],
          },
          message: nullable({ type: "string" }),
          reasonCode: nullable({
            type: "string",
            enum: [
              "wrong_eligibility",
              "wrong_high",
              "wrong_low",
              "wrong_condition",
              "missing_condition",
              "profile_wrong",
              "wrong_company_fact",
              "criteria_wrong",
              "taxonomy_gap",
              "duplicate_grant",
              "stale_grant",
              "portal_blocked",
              "rejected_at_eligibility",
              "accepted_for_review",
              "selected",
              "rejected",
              "other",
            ],
          }),
          outcome: nullable({
            type: "string",
            enum: ["pending", "selected", "rejected", "blocked"],
          }),
          occurredAt: nullable({ type: "string", format: "date-time" }),
          correction: nullable(ref("MatchFeedbackCorrection")),
          payload: nullable({ type: "object", additionalProperties: true }),
        },
        additionalProperties: false,
      },
      MatchFeedbackCorrection: {
        type: "object",
        properties: {
          dimension: nullable({
            type: "string",
            enum: CRITERION_DIMENSION_ENUM,
          }),
          criterionId: nullable({ type: "string" }),
          expectedEligibility: nullable({ type: "string", enum: ["eligible", "conditional", "ineligible"] }),
          correctedEligibility: nullable({ type: "string", enum: ["eligible", "conditional", "ineligible"] }),
          correctedResult: nullable({ type: "string", enum: ["pass", "fail", "unknown"] }),
          note: nullable({ type: "string" }),
        },
        additionalProperties: false,
      },
      FeedbackReceipt: {
        type: "object",
        required: ["id", "receivedAt"],
        properties: {
          id: { type: "string" },
          receivedAt: { type: "string", format: "date-time" },
        },
        additionalProperties: false,
      },
      FeedbackResult: {
        type: "object",
        required: ["receipt"],
        properties: {
          receipt: ref("FeedbackReceipt"),
        },
        additionalProperties: false,
      },
      MatchEventRequest: {
        type: "object",
        properties: {
          event: { type: "string", enum: ["surfaced", "clicked", "saved", "apply_click"] },
          type: {
            type: "string",
            enum: ["surfaced", "clicked", "saved", "apply_click"],
            deprecated: true,
          },
          rulesetVer: { type: "string" },
          payload: { type: "object", additionalProperties: true },
        },
        additionalProperties: false,
      },
      MatchEventResult: {
        type: "object",
        required: ["accepted", "companyId", "grantId", "event", "receipt"],
        properties: {
          accepted: { type: "boolean" },
          companyId: { type: "string" },
          grantId: { type: "string" },
          event: { type: "string", enum: ["surfaced", "clicked", "saved", "apply_click"] },
          receipt: ref("MatchEventReceipt"),
        },
        additionalProperties: false,
      },
      MatchEventReceipt: {
        type: "object",
        required: ["id", "acceptedAt"],
        properties: {
          id: { type: "string" },
          acceptedAt: { type: "string", format: "date-time" },
        },
        additionalProperties: false,
      },
      ConsentRecord: {
        type: "object",
        required: ["scope", "purpose", "grantedAt", "revokedAt"],
        properties: {
          scope: { type: "string", enum: ["basic_info", "hometax", "insurance"] },
          purpose: { type: "string" },
          grantedAt: { type: "string", format: "date-time" },
          revokedAt: nullable({ type: "string", format: "date-time" }),
        },
        additionalProperties: false,
      },
      ConsentListResult: {
        type: "object",
        required: ["companyId", "consents"],
        properties: {
          companyId: { type: "string" },
          consents: arrayOf(ref("ConsentRecord")),
        },
        additionalProperties: false,
      },
      ConsentGrantRequest: {
        type: "object",
        required: ["scope"],
        properties: {
          scope: { type: "string", enum: ["basic_info", "hometax", "insurance"] },
          purpose: { type: "string" },
        },
        additionalProperties: false,
      },
      ConsentGrantResult: {
        type: "object",
        required: ["consent"],
        properties: {
          consent: ref("ConsentRecord"),
        },
        additionalProperties: false,
      },
      ConsentRevokeResult: {
        type: "object",
        required: ["scope", "revoked"],
        properties: {
          scope: { type: "string", enum: ["basic_info", "hometax", "insurance"] },
          revoked: { type: "boolean" },
        },
        additionalProperties: false,
      },
      NotificationItem: {
        type: "object",
        required: ["id", "kind", "title", "body", "priority", "target", "rulesetVer"],
        properties: {
          id: { type: "string" },
          kind: {
            type: "string",
            enum: ["deadline", "new_match", "soon_eligible", "needs_input"],
          },
          title: { type: "string" },
          body: { type: "string" },
          priority: { type: "string", enum: ["low", "medium", "high"] },
          target: { type: "string" },
          grantId: { type: "string" },
          dDay: nullable({ type: "integer" }),
          etaDate: nullable({ type: "string" }),
          rulesetVer: { type: "string" },
        },
        additionalProperties: false,
      },
      NotificationFeedResult: {
        type: "object",
        required: ["generatedAt", "notifications"],
        properties: {
          generatedAt: { type: "string" },
          notifications: arrayOf(ref("NotificationItem")),
        },
        additionalProperties: false,
      },
      NotificationReceiptRequest: {
        type: "object",
        required: ["notificationId", "action"],
        properties: {
          notificationId: { type: "string" },
          action: { type: "string", enum: ["read", "dismiss"] },
        },
        additionalProperties: false,
      },
      NotificationReceiptItem: {
        allOf: [
          ref("NotificationItem"),
          {
            type: "object",
            required: ["status", "readAt", "dismissedAt"],
            properties: {
              status: { type: "string", enum: ["unread", "read", "dismissed"] },
              readAt: nullable({ type: "string" }),
              dismissedAt: nullable({ type: "string" }),
            },
            additionalProperties: false,
          },
        ],
      },
      NotificationReceiptResult: {
        type: "object",
        required: ["notification"],
        properties: {
          notification: ref("NotificationReceiptItem"),
        },
        additionalProperties: false,
      },
      NotificationSettings: {
        type: "object",
        required: ["deadlineReminder", "newMatch", "quietHoursStart", "quietHoursEnd"],
        properties: {
          deadlineReminder: { type: "boolean" },
          newMatch: { type: "boolean" },
          quietHoursStart: nullable({ type: "string" }),
          quietHoursEnd: nullable({ type: "string" }),
        },
        additionalProperties: false,
      },
      DeviceRegistrationRequest: {
        type: "object",
        required: ["deviceId", "platform", "pushToken"],
        properties: {
          deviceId: { type: "string" },
          platform: { type: "string", enum: ["ios", "android"] },
          pushToken: { type: "string" },
        },
        additionalProperties: false,
      },
      DeviceResult: {
        type: "object",
        required: ["deviceId", "platform", "registered"],
        properties: {
          deviceId: { type: "string" },
          platform: { type: "string", enum: ["ios", "android"] },
          registered: { type: "boolean" },
        },
        additionalProperties: false,
      },
      DeleteDeviceResult: {
        type: "object",
        required: ["deleted"],
        properties: {
          deleted: { type: "boolean" },
        },
        additionalProperties: false,
      },
      AppTokenEnvelope: envelope(ref("AppTokenResponse")),
      LogoutEnvelope: envelope(ref("LogoutResult")),
      CompanyListEnvelope: envelope(ref("CompanyListResult")),
      CompanyEnvelope: envelope(ref("CompanyResult")),
      CompanyProfileEnvelope: envelope(ref("CompanyProfileResult")),
      CompanyProfileUpdateEnvelope: envelope(ref("CompanyProfileUpdateResult")),
      CompanyEnrichmentEnvelope: envelope(ref("CompanyEnrichmentResult")),
      CompanyMatchesEnvelope: envelope(ref("CompanyMatchesResult")),
      ActionQueueEnvelope: envelope(ref("ActionQueueResult")),
      NextQuestionEnvelope: envelope(nullable(ref("NextQuestion"))),
      RoadmapEnvelope: envelope(ref("RoadmapResult")),
      ApplySheetEnvelope: envelope(ref("ApplySheet")),
      FeedbackEnvelope: envelope(ref("FeedbackResult")),
      MatchEventEnvelope: envelope(ref("MatchEventResult")),
      ConsentListEnvelope: envelope(ref("ConsentListResult")),
      ConsentGrantEnvelope: envelope(ref("ConsentGrantResult")),
      ConsentRevokeEnvelope: envelope(ref("ConsentRevokeResult")),
      NotificationFeedEnvelope: envelope(ref("NotificationFeedResult")),
      NotificationReceiptEnvelope: envelope(ref("NotificationReceiptResult")),
      NotificationSettingsEnvelope: envelope(ref("NotificationSettings")),
      DeviceEnvelope: envelope(ref("DeviceResult")),
      DeleteDeviceEnvelope: envelope(ref("DeleteDeviceResult")),
    },
  },
} as const;

export type AppV1OpenApi = typeof appV1OpenApi;
export type AppV1OpenApiRoutePath = (typeof appV1OpenApiRoutePaths)[number];
