export const REQUIRED_TABLES = [
  "users",
  "accounts",
  "sessions",
  "verification_tokens",
  "app_refresh_tokens",
  "app_devices",
  "notification_settings",
  "companies",
  "user_company",
  "company_profiles",
  "company_enrichment_cache",
  "consents",
  "grants",
  "grant_raw",
  "grant_criteria",
  "grant_attachment_archives",
  "source_cursor",
  "dedup_links",
  "match_state",
  "match_events",
  "feedback",
  "extraction_log",
  "golden_set",
  "eval_runs",
  "grant_insight_snapshots",
] as const;

export const RLS_TABLES = [
  "companies",
  "user_company",
  "company_profiles",
  "consents",
  "app_refresh_tokens",
  "app_devices",
  "notification_settings",
  "match_state",
  "match_events",
] as const;
