import assert from "node:assert/strict";
import { checkWritingConsistency } from "./writingConsistency";
const section = (text: string, fieldId = "a") => ({ fieldId, label: fieldId, text });
const check = (sections: ReturnType<typeof section>[], budget = "", projectName = "새 사업") => checkWritingConsistency({ projectName, budget, sections });
assert.equal(check([section("사업명: 옛 사업")]).issues[0]?.kind, "project_name");
assert.equal(check([section("사업명: 새 사업")]).issues.length, 0);
assert.equal(check([section("2025년 매출액: 1억원"), section("2025년 매출: 100,000,000원", "b")]).issues.length, 0);
assert.equal(check([section("2025년 매출: 1억원"), section("2026년 매출: 2억원", "b")]).issues.length, 0);
assert.equal(check([section("2025년 매출: 1억원"), section("2025년 목표매출: 2억원", "b")]).issues.length, 0);
assert.equal(check([section("2025년 매출: 1억원"), section("2025년 매출: 2억원", "b")]).issues[0]?.kind, "conflicting_value");
assert.equal(check([], "총사업비: 1억원\n정부지원금: 7천만원\n자부담: 3000만원").issues.length, 0);
assert.equal(check([], "총사업비: 1억원\n정부지원금: 7천만원\n자부담: 2000만원").issues[0]?.kind, "budget_total");
assert.equal(check([], "총사업비: 1억원\n정부지원금: 7천만원").issues.length, 0);
assert.equal(check([section("총사업비: 1억원"), section("정부지원금: 7천만원\n자부담: 2천만원", "b")]).issues.length, 0);
assert.equal(check([section("사업기간: 2026-10-01 ~ 2026-09-01")]).issues[0]?.kind, "date_order");
assert.equal(check([section("사업기간: 2026-02-30 ~ 2026-01-01")]).issues.length, 0, "잘못된 날짜를 정상 날짜로 보정하지 않는다");
assert.equal(check([section("매출: 1억 5000만원\n직원수: 약 3명\n앞으로 매출 2억원을 목표로 합니다.")]).recognizedValues, 0, "명확하지 않은 단위·자유 문장은 추측하지 않는다");
assert.equal(check([section("매출액: 0.5억원"), section("매출액: 5000만원", "b")]).issues.length, 0);
console.log("PASS: manuscript consistency checks explicit project names, date order, comparable year/metric values and bounded exact budget arithmetic; no inference for ambiguous prose, missing components or different periods");
