import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {tmpdir} from 'node:os';
import {createServer} from 'node:http';
const root=resolve(new URL('../..',import.meta.url).pathname), out=join(root,'docs/evidence/demo-chat-20261001',new Date().toISOString().replace(/[:.]/g,'-'));
const req=createRequire(join(root,'apps/web/package.json')), esbuild=createRequire(createRequire(import.meta.url).resolve('tsx/package.json'))('esbuild');
const bundleRoot=mkdtempSync(join(tmpdir(),'demo-chat-'));
const exec=promisify(execFile), session='demo-chat-'+process.pid;
const browser=async(args,input)=>{if(input){const p=execFile('agent-browser',['--session',session,...args],{maxBuffer:20e6,timeout:30000});p.stdin.end(input); return await new Promise((res,rej)=>{let s='',e='';p.stdout.on('data',v=>s+=v);p.stderr.on('data',v=>e+=v);p.on('close',c=>c?rej(Error(e||s)):res(s));});}return (await exec('agent-browser',['--session',session,...args],{maxBuffer:20e6,timeout:30000})).stdout;};
const evaluate=async(code)=>{const value=JSON.parse(await browser(['eval','--stdin'],code));return value;};
mkdirSync(out,{recursive:true});
await esbuild.build({entryPoints:[join(root,'tools/demo-chat-review/entry.tsx')],bundle:true,platform:'browser',format:'iife',outfile:join(bundleRoot,'fixture.js'),tsconfig:join(root,'apps/web/tsconfig.json'),jsx:'automatic',define:{'process.env.NODE_ENV':'"development"'},nodePaths:[join(root,'apps/web/node_modules')],alias:{'@cunote/core':join(root,'tools/design-company-review/core.ts'),'next/navigation':join(root,'tools/design-company-review/navigation.ts')}});
const css=await req('postcss')([req('@tailwindcss/postcss')({base:join(root,'apps/web')})]).process(readFileSync(join(root,'apps/web/src/app/globals.css'),'utf8'),{from:join(root,'apps/web/src/app/globals.css')});
writeFileSync(join(bundleRoot,'fixture.css'),css.css);
const server=createServer((request,response)=>{const file=request.url?.split('?')[0];response.setHeader('content-type',file==='/fixture.js'?'text/javascript; charset=utf-8':file==='/fixture.css'?'text/css; charset=utf-8':'text/html; charset=utf-8');response.end(file==='/fixture.js'||file==='/fixture.css'?readFileSync(join(bundleRoot,file.slice(1))):'<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/fixture.css"><div id="root"></div><script>window.process={env:{NODE_ENV:"development"}};window.errors=[];window.addEventListener("error",e=>window.errors.push(e.message))</script><script src="/fixture.js"></script></html>');});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url='http://127.0.0.1:'+server.address().port+'/?companyId=company-A';
const sourceSha=(await exec('git',['rev-parse','HEAD'],{cwd:root})).stdout.trim();
const sourceDiff=(await exec('git',['diff','--','apps/web/src'],{cwd:root,maxBuffer:20e6})).stdout;
const report={sourceSha,sourceDiffSha256:createHash('sha256').update(sourceDiff).digest('hex'),fixture:true,externalWrites:0,actualSourceComponents:true,sourceFiles:Object.fromEntries(['apps/web/src/features/apply-workspace/WorkspaceView.tsx','apps/web/src/features/apply-workspace/ChatPanel.tsx'].map(path=>[path,createHash('sha256').update(readFileSync(join(root,path))).digest('hex')])),checks:[],screenshots:[]};
try {
 await browser(['open',url]); await browser(['set','viewport','1440','1100']);
 await browser(['wait','[data-general-grant-chat]']);
 const click=async(selector)=>{await browser(['click',selector]);};
 const count=async(selector)=>await evaluate(`document.querySelectorAll(${JSON.stringify(selector)}).length`);
 if(!(await evaluate(`document.body.textContent`)).includes('작성 항목 분석이 연결되지 않았어요'))throw Error('Expected ladder b missing-field state');
 report.checks.push('ordinary persistent RHWP ladder b without field bindings offers AI chat');
 await browser(['screenshot',join(out,'ladder-b-1440.png'),'--full']); report.screenshots.push('ladder-b-1440.png');
 await click('[data-general-grant-chat]'); await browser(['wait','[role="dialog"]']);
 await browser(['fill','[aria-label="채팅 입력"]','지원서 제출 전에 무엇을 확인해야 하나요?']);
 await click('[aria-label="보내기"]');
 await browser(['wait','--fn',"document.body.textContent.includes('합성 SSE 응답:')"]);
 const requests=await evaluate(`window.designAudit.requests.filter(r=>r.path.includes('/api/web/chat'))`);
 if(requests.length!==1||requests[0].body.message.text!=='지원서 제출 전에 무엇을 확인해야 하나요?')throw Error('Unexpected chat request');
 if(requests[0].body.message.fieldContext||requests[0].body.context.draftId)throw Error('General advice leaked field context or draft');
 report.checks.push('actual ChatPanel submits grant-only context without field binding and renders synthetic SSE answer');
 await browser(['screenshot',join(out,'general-chat-1440.png'),'--full']); report.screenshots.push('general-chat-1440.png');
 await browser(['fill','[aria-label="채팅 입력"]','닫았다 열어도 유지할 질문']);
 await click('[data-slot="dialog-close"]');
 await browser(['wait','--fn',"!document.querySelector('[role=dialog]')"]);
 await click('[data-general-grant-chat]'); await browser(['wait','[role="dialog"]']);
 if(await evaluate(`document.querySelector('[aria-label="채팅 입력"]').value`)!=='닫았다 열어도 유지할 질문')throw Error('Close/reopen lost unsent question');
 if(!(await evaluate(`document.body.textContent`)).includes('합성 SSE 응답:'))throw Error('Close/reopen lost messages');
 report.checks.push('close/reopen retains messages and unsent input');
 await browser(['set','viewport','390','844']); await browser(['wait','350']);
 const layout=await evaluate(`({body:document.body.scrollWidth,width:innerWidth,dialog:document.querySelector('[role=dialog]').getBoundingClientRect().toJSON()})`);
 report.mobileLayout=layout;
 if(layout.dialog.width>layout.width)throw Error('Mobile dialog horizontal overflow '+JSON.stringify(layout));
 await browser(['screenshot',join(out,'general-chat-390.png'),'--full']); report.screenshots.push('general-chat-390.png');
 report.checks.push('mobile 390 dialog fits viewport');
 await click('[data-slot="dialog-close"]'); await browser(['wait','--fn',"!document.querySelector('[role=dialog]')"]);
 await click('[data-fixture-preview]'); await browser(['wait','--fn',"document.body.textContent.includes('관리자 RHWP 작성 시뮬레이션')"]);
 if(await count('[data-general-grant-chat]')||await count('[role="dialog"]'))throw Error('Preview exposes chat trigger/dialog');
 if((await evaluate(`window.designAudit.requests.filter(r=>r.path.includes('/api/web/chat')).length`))!==1)throw Error('Preview caused chat request');
 report.checks.push('read-only admin preview has no chat trigger/dialog and starts no chat request');
 await browser(['screenshot',join(out,'preview-no-chat-390.png'),'--full']); report.screenshots.push('preview-no-chat-390.png');
 const errors=await evaluate('window.errors');if(errors.length)throw Error(errors.join(';'));
 report.checks.push('no browser runtime errors');
 report.audit=await evaluate('window.designAudit'); report.ok=true;
 report.boundary='UI-only synthetic SSE, source-file API unavailable by design; no real LLM/API/auth/HWPX editing/persistence acceptance claimed.';
} catch(error) { report.ok=false;report.error=String(error);throw error; }
finally { writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2));await browser(['close']).catch(()=>{});await new Promise(r=>server.close(r));rmSync(bundleRoot,{recursive:true,force:true}); }
console.log(JSON.stringify({ok:report.ok,out,checks:report.checks}));
